apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc
  namespace: tp-prod
  labels:
    app: webmvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: jobs-api
                topologyKey: kubernetes.io/hostname
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: applicants-api
                topologyKey: kubernetes.io/hostname
      containers:
        - name: webmvc
          image: tpfinal.azurecr.io/webmvc:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "4m"
              memory: "900Mi"
            limits:
              cpu: "1"
              memory: "2000Mi"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc
  namespace: tp-prod
  labels:
    app: webmvc
spec:
  type: ClusterIP
  selector:
    app: webmvc
  ports:
    - name: http
      port: 80
      targetPort: 80
